AMSTER_LIB_NAME = GAMELIFEBBQt

AMSTER_LIB_DEPENDS += \
    amsterqt \

win32{
    DEFINES += GAMELIFEQT_GENERATOR_DLLEXPORT=__declspec(dllimport)
}else{
    DEFINES += GAMELIFEQT_GENERATOR_DLLEXPORT=
}
